version: '3.8'

services:
  finsync:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./assets:/root/assets
      - ./templates:/root/templates
    restart: always
